### ISSUE TITLE
Transactions included in calculations

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Dashboard#203]
The methodologies:
http://support.iatistandard.org/entries/51980199-Timeliness-Frequency
http://support.iatistandard.org/entries/52291815-Timeliness-Time-lag

Don't specify which types of transactions should be included. Should it be all of them? (this is what I'm using currently)

**Comment by dalepotter** [comment]
It seems that this issue is no longer relevant, as all types of transactions are used in the assessment: https://github.com/IATI/IATI-Stats/blob/master/stats/dashboard.py#L820-L825

The exception is future transaction dates, but these are already noted in the text and with a red flag. Perhaps this should still be made clearer though - @iatisupport or @bill-anderson may have some thoughts - otherwise, suggest this issue be closed.

**Comment by iatisupport** [comment]
As all types of transactions are used here I am happy for this issue to be closed. Also a recommendation for handling future dates has been made at https://github.com/IATI/IATI-Dashboard/issues/223
