### ISSUE TITLE
Location Data Published But Zero On Comprehensiveness Page

### ISSUE THREAD

**Issue by iatisupport** [IATI/IATI-Dashboard#369]
The US have included some location data in their published datafiles - see http://beta.foreignassistance.gov/assets/IATI/MCC_Tanzania.xml. However the score for location data on the 'added value' tab of the comprehensiveness page is zero - http://dashboard.iatistandard.org/comprehensiveness_valueadded.html

**Comment by dalepotter** [comment]
Current investigations show that all activities in this xml file may not be considered to be current, for the purposes of calculating comprehensiveness scores.

I have added an issue to output a list here: https://github.com/IATI/IATI-Stats/issues/74

**Comment by dalepotter** [comment]
Just following up on this, now that the list of activities classed as 'current' for comprehensiveness assessments has been generated - for example for this file: http://dashboard.iatistandard.org/stats/current/aggregated-file/unitedstates/unitedstates-tz2/comprehensiveness_current_activities.json

Looking at the [MCC_Tanzania.xml](http://beta.foreignassistance.gov/assets/IATI/MCC_Tanzania.xml) file, this contains 13 `<pos>` elements across 8 activities:

`US-18-TZA-2750BXCOMD-ENRGY SCTR-154` (1 `<pos>` element)
`US-18-TZA-2750BXCOMD-ENRGY SCTR-155` (1 `<pos>` element)
`US-18-TZA-2750BXCOMD-ENRGY SCTR-156` (6 `<pos>` elements)
`US-18-TZA-2750BXCOMD-TRSPRT STR-159` (1 `<pos>` element)
`US-18-TZA-2750BXCOMD-TRSPRT STR-271` (1 `<pos>` element)
`US-18-TZA-2750BXCOMD-WTR SECTOR-236` (1 `<pos>` element)
`US-18-TZA-2750BXCOMD-WTR SECTOR-237` (1 `<pos>` element)
`US-18-TZA-2750BXCOMD-WTR SECTOR-273` (1 `<pos>` element)

However, none of these activities are classed as current, hence they will not contribute to scores.  As noted in https://github.com/IATI/IATI-Dashboard/issues/371, it is worth showing the count of activities on the dashboard pages themselves - in order to improve user understanding of these assessments.

With this in mind, I'll close this ticket.  Do let me know if there is more data to investigate.
