### ISSUE TITLE
Capture Regular Publishing Statistics To Enable Tracking Of Publisher Data Quality

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Dashboard#373]
it would be useful to regularly capture the figures available for the Transparency Indicator summary at http://dashboard.iatistandard.org/transparencyindicator.html  in order to enable the tracking of individual publisher's published file data quality over time

**Comment by iatisupport** [comment]
Initially we can implement this by adding two extra columns to the TI summary page. One column would hold the publisher's overall score as at 3 months ago and the other 12 months ago. Each figure should include an up or down arrow relevant to the publisher score as at 'today' and the figures would be updated each day on a rolling basis.

it would also be useful to investigate backloading of any data we have so that when this enhancement goes live publishers don't have to wait 3 months before they start seeing if their data has improved or not.
