### ISSUE TITLE
Exclude Secondary Publishers From Existing Transparency Indicator Scoring

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Dashboard#385]
As secondary publishers are publishing information that is provided to them by other organisations they should currently be excluded from the current Transparency Indicator Score Tables.

**Comment by dalepotter** [comment]
Suggestion is to:

- Have a list `"publisher_source_type": "secondary_source", ` in the [ckan API output](http://dashboard.iatistandard.org/stats/ckan.json). @iatisupport to ensure that the field is set for known secondary publishers.
- Secondary publishers to not appear in the any publisher stats
- Add a note in the text to state that secondary publishers are not assessed in the publisher statistics pages

**Comment by iatisupport** [comment]
I have now checked that the field 'Source' on each publisher's Registry account is set to 'Secondary source' for:

Aiddata
OCHA Financial Tracking Service (FTS)
Interaction NGO Aid Map

**Comment by dalepotter** [comment]
Have just begun looking to implement this now. After some investigation, I would suggest an alternative approach to test for 'secondary publishers'. 

Rather than base this on the field in the registry, I would suggest that activities marked with the reporting-org set to secondary publisher (i.e. `iati-activities/iati-activity/reporting-org/@secondary-reporter` = `1`) be excluded from the publisher stats. If a publisher has no activities based on this test, then they are omitted from the publisher statistics tables.

An alternative approach is to make an publisher-wide decision, (i.e. if `iati-organisations/iati-organisation/reporting-org/@secondary-reporter` = `1`). Note that not all publishers have an organisation file, for example `Interaction NGO Aid Map`.

**Comment by iatisupport** [comment]
Thanks Dale and I agree that this would actually be a better approach. We do have some publishers who publish both their own data and that of other organisations so this would still enable those organisations to get a valid score for their own reporting

**Comment by dalepotter** [comment]
Sound good, will base the secondary publisher test on if `iati-activities/iati-activity/reporting-org/@secondary-reporter` = `1`.

**Comment by dalepotter** [comment]
Following clarification from @iatisupport, publishers who publish 100% of their activities as a secondary reporter will be removed from the coverage as well as transparency indicator tables.

**Comment by dalepotter** [comment]
Remaining action is to add a test for `_is_secondary_reported()`

**Comment by hayfield** [comment]
@dalepotter Is this still an issue?
