### ISSUE TITLE
Score Publishers With No Reference Data as 20%

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Dashboard#392]
All publishers have now been contacted to ask for valid reference data to use in the coverage calculations. Therefore all publishers who have not as yet provided reference data should receive a coverage score of 20% and a red flag

**Comment by iatisupport** [comment]
just to add that any publishers who have started publishing to IATI since the recent coverage exercise took place and therefore do not have any reference data (and are not included in the reference data sheet), they should also be scored with 20% and also marked as a 'new publisher' by marking their score with a green flag
