### ISSUE TITLE
Graphs not updating

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Dashboard#402]
Looking at the publisher graph, it doesn't seem to be the case that the upper value has updated to reflect the fact that there are 450+ publishers: http://dashboard.iatistandard.org/publishers.html - is this a glitch or designed in, maybe?

**Comment by dalepotter** [comment]
Thanks for flagging this. This graph is not updating correctly due to persistent issues in the running of the the gitaggregate process - raw data that powers the graphs here: http://dashboard.iatistandard.org/stats/gitaggregate-dated/publishers.json  (last successful update was 2016-04-16).

Unfortunately there has been limited time to get to the bottom of such issues on account of a big push towards various fixes and methodology changes for the work on the Global Partnership transparency indicator and associated coverage scoring.

There are a number of other runtime Dashboard runtime issues which we hope to get this resolved when time allows!

**Comment by dalepotter** [comment]
Just as an update to this one... Due to an increase in server memory, the [underlaying stats do appear to be updating more frequently](http://dashboard.iatistandard.org/stats/gitaggregate-dated/publishers.json) over the past few days. As a result of this, the publisher graph is more up-to-date at present:

![image](https://cloud.githubusercontent.com/assets/8247168/15468726/b0d2500a-20dd-11e6-9ff1-bdfdca23edac.png)

We'll keep an eye on this and there may be capacity to further analyse the performance of the code when work towards the Global Partnership transparency indicator and associated coverage scoring has concluded.

**Comment by dalepotter** [comment]
Closing this issue as the data behind the graphs is now being updated.
