### ISSUE TITLE
Include Sector, Region, Country & Aid Type Held At Transaction Level In Dashboard Assessments

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Dashboard#407]
Currently instances of the elements sector, recipient-region, recipient- country & aid type are only counted in the publishing statistics if they are present at the activity element level. However, some publishers now publish this information at the transaction level instead and so this information should also be counted and included in the publishing statistic assessments

**Comment by PetyaKangalova** [comment]
Following discussion with @bill-anderson  [IATI/Tech-Support-Q-A Private/#7](https://github.com/IATI/Tech-Support-Q-A/issues/7), it was agreed that the following amendments need to be made to the Dashboard:

1.  Incorporate elements reported at transaction level.
A number of elements are not currently picked up by the Dashboard as they are reported at [transaction ](http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/transaction/) as opposed to activity level.  

![image](https://cloud.githubusercontent.com/assets/24607542/26629762/c56d0336-45fb-11e7-87de-1113851f8009.png)

2. Recipient language
Recipient language is currently only picking up `xml:lang `reported at `title` and `description`. If `xml:lang` is not reported there, then the Dashboard should pick up the default language.

**Comment by wendyrogers** [comment]
This is also an issue for the Grand Bargain Transparency dashboard as the DAC sector code is used to identify if an activity is assessed as 'humanitarian' or not. Therefore it would be good to get this issue resolved ASAP at least with regard to the DAC sector codes

**Comment by dalepotter** [comment]
Just looking at this one afresh - to be fully clear, are we saying that an activity such as this should score positively under sector methodology?

- https://github.com/IATI/IATI-Stats/blob/master/stats/tests/test_comprehensiveness.py#L1629-L1674
- https://github.com/IATI/IATI-Stats/blob/master/stats/tests/test_comprehensiveness.py#L1445-L1498 (i.e. `sector` element **not present** at activity level, but **present** for all transactions)

Inversely, are we saying that this activity should not score under the sector methodology?
- https://github.com/IATI/IATI-Stats/blob/master/stats/tests/test_comprehensiveness.py#L1537-L1589 (i.e. `sector` element **not present** at activity level, and **not present** for all transactions)

I presume the same results should apply for the [comprehensiveness 'Country or Region' metric](http://dashboard.iatistandard.org/comprehensiveness_core.html)? Whilst there is a field in transaction for `description`, I would not suggest updating the methodology for the [comprehensiveness 'Description' metric](http://dashboard.iatistandard.org/comprehensiveness_core.html), and base this only on the presence of a `description` element at the activity level.

Are there any other [Dashboard metrics](http://dashboard.iatistandard.org/comprehensiveness_core.html) to look at with regard to scoring elements contained within a `transaction`?

In order to focus on one thing at a time, I would then suggest we look at recipient language methodology once this one is resolved...

**Comment by PetyaKangalova** [comment]
@dalepotter  It is my understanding that the above methodology is correct for `sector`, `recipient country` , `recipient region` and `aid-type`. I am not aware of any other Dashboard metrics that you need to look at with regards to scoring elements contained within a `transaction` under the comprehensiveness score.

  @wendyrogers @bill-anderson  Is there anything that I am missing? I am aware that [humanitarian](http://iatistandard.org/202/activity-standard/overview/humanitarian-reporting/) also needs to be incorporated at both activity and transaction level, but this is not under the comprehensiveness tests, right?

**Comment by hayfield** [comment]
IATI/IATI-Stats#109 IATI/IATI-Stats#110 #444 

The above resolves this for sectors.

Updated documentation needs deploying.
