### ISSUE TITLE
Humanitarian dashboard: Publishers can score more than 100 for clusters

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Dashboard#485]
[Moved from IATI/IATI-Stats#124.]

The ‘Clusters’ measure is calculated as a proportion of ‘Number of Activities’. But the number of activities definition is independent of clusters. So it’s possible to score more than 100, as is the case here:

![screen shot 2018-05-23 at 22 06 18](https://user-images.githubusercontent.com/464193/40451156-93001ce6-5ed5-11e8-8c24-fe1c38697807.png)

This also affects the average, which assumes a maximum score of 100 for each of the four indicators.

Amending the definition for “Number of Activities”, to include activities where `sector/@vocabulary="10"` would resolve this.

**Comment by wendyrogers** [comment]
Hi @andylolz thanks for flagging and I just wanted to confirm that our thinking here is the same? 

This column should be calculated  by counting those activities that are assessed as being humanitarian (ie humanitarian indicator is set or a humanitarian DAC sector code has been specified) AND have at least 1 cluster code specified (sector/@vocabulary="10") and then assessing the total number of 'activities with cluster codes' as a percentage of ALL 'humanitarian' activities.

I think our logic is the same but just wanted to double check?

**Comment by andylolz** [comment]
Hi Wendy!

I’m not sure… I can’t tell if we’re on exactly the same page. Let me try and put it another way.

So at the moment, the definition of “Number of activities” is the following:

> Total number of humanitarian activities (determined by use of `iati-activity/@humanitarian` attribute or `<humanitarian-scope>` element or DAC 5-digit sector codes between `72010` to `74010` inclusive, or DAC 3-digit sector codes `720`, `730` or `740`).

I’m proposing changing it in the following way:

> Total number of humanitarian activities (determined by use of `iati-activity/@humanitarian` attribute or `<humanitarian-scope>` element or DAC 5-digit sector codes between `72010` to `74010` inclusive, or DAC 3-digit sector codes `720`, `730` or `740`, **or use of `sector/@vocabulary="10"`**).

The clusters definition would then remain unchanged:

> Use of `sector/@vocabulary="10"` - proportion of the number of activities.

**Comment by wendyrogers** [comment]
Thanks for the update @andylolz and I think we have now clarified that the original definition of whether an activity is 'humanitarian' (or not) will still stand due to the definition having been generally accepted via the consultation for the Grand Bargain Transparency Dashboard methodology . 

"Total number of humanitarian activities (determined by use of iati-activity/@humanitarian attribute or <humanitarian-scope> element or DAC 5-digit sector codes between 72010 to 74010 inclusive, or DAC 3-digit sector codes 720, 730 or 740)."

This means that if an activity has a <humanitarian-scope> element but neither the @humanitarian element or relevant DAC sector code is present it will' **NOT** be considered as a 'humanitarian' activity.

However, the cluster value currently being calculated is still incorrect and needs amending so that it is calculated as the % of humanitarian activities that have at least 1 instance of a cluster code specified ie sector/@vocabulary="10"  This value needs to be a percentage so that the Average value can also be calculated correctly.

**Comment by andylolz** [comment]
Okay I think I see how I got confused now. Here’s the definition of “number of activities” provided on [the IATI humanitarian dashboard](http://dashboard.iatistandard.org/humanitarian.html#h_narrative):

> Total number of humanitarian activities (determined by use of `iati-activity/@humanitarian` attribute or `<humanitarian-scope>` element or DAC 5-digit sector codes between `72010` to `74010` inclusive, or DAC 3-digit sector codes `720`, `730` or `740`).

So that definition *does* include `humanitarian-scope` :confused: Does that sound correct, @wendyrogers, or is that a typo? I might just be confusing myself here, and I don’t want to introduce more confusion!

**Comment by wendyrogers** [comment]
Good spot @andylolz and no that is not correct and also needs to be amended to remove reference to humanitarian-scope :-(

**Comment by wendyrogers** [comment]
All good and thanks for reverting #130 (via #493) Andy and I suggest that once we have fixes for this and the other related issues we initially load them to the [development version of the IATI dashboard](http://dev.dashboard.iatistandard.org/publishing_stats.html) so we can check that everything looks as expected before releasing to the live dashboard site.

**Comment by andylolz** [comment]
Just noticed that #133 has now been deployed, so this is now fixed :clap: Maximum score for clusters is currently 98 👍 

![screenshot 2019-02-05 at 12 14 40](https://user-images.githubusercontent.com/464193/52272793-c10c5480-293f-11e9-8bcf-549bbc9b87e6.png)
