### ISSUE TITLE
Store Historical Summary Stats

### ISSUE THREAD

**Issue by c-s-campbell** [IATI/IATI-Dashboard#574]
We find these (http://publishingstats.iatistandard.org/summary_stats.html) IATI scores useful to see how the organisations we fund perform in transparency and would like to track this over time. It seems like a fairly easy ask and would help lots. Any help on this would be much appreciated.

Thanks,

Calum

**Comment by PetyaKangalova** [comment]
Thank you for raising this issue @c-s-campbell ! We understand that such an enhancement to the IATI dashboard might be useful for some users, but at this point in time we will not be working on enhancements for the IATI Dashboard.  I have labelled this issue as an 'Enhacement' so that we can review in the new year once plans for the IATI dashboard work are clarified.

In the meantime there is something called http://web.archive.org/ which might provide you with some historic record. IATI has no control over it, but it might be useful.

If you go to http://web.archive.org/ and enter the dashboard.iatistandard.org url in the search, you should be able to see a calendar of available snapshots, selecting any of them will bring up the dashboard with the exact data that was available at that date. There are plenty of snapshots for 2018, and one early in 2019 that should give an approximation to some of the results you are looking for.
